frequency: 10

two_d_mode: true

publish_tf: false # false for mapping; true for localizalization

odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: map #uncomment for mapping

#odom0: /noisy_odom
#odom0_config: [ false, false, false,
#                false, false, true, 
#                true, true, false,
#                false, false, true,
#                false, false, false]
#odom0_differential: false

odom0: /noisy_odom
odom0_config: [ true, true, false,
                false, false, true, 
                false, false, false,
                false, false, false,
                false, false, false]
odom0_differential: true


#imu0: /rs_t265/imu
#imu0_config: [ false, false, false,
#                false, false, true, 
#                false, false, false,
#                false, false, true,
#                true, false, false]
#imu0_differential: false

odom1: /rs_t265/odom/sample
odom1_config: [ false, false, false,
                false, false, true, 
                false, false, false,
                false, false, true,
                true, false, false]
odom1_differential: false