robot_base_frame: base_link
transform_tolerance: 0.4
update_frequency: 5.0
publish_frequency: 1.0
obstacle_range: 3.0 
#mark_threshold: 1
publish_voxel_map: true
resolution: 0.05

navigation_map:
  map_topic: /map
  subscribe_to_updates: true
    
obstacles:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
